version: 2.1

orbs:
  unity: game-ci/unity@1.4

workflows:
  build-unity-project:
    jobs:
      # WebGL
      - unity/build:
          name: 'build-webgl'
          step-name: 'Build WebGL'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'webgl'
            editor_version: '2021.3.1f1'
            resource_class: 'large'
          project-path: '.'
          build-target: 'WebGL'
          compress: false
          context: unity