version: 2.1

orbs:
  unity: game-ci/unity@1.4

workflows:
  build-unity-project:
    jobs:
           # WebGL
      - unity/build:
          name: 'build-webgl'
          step-name: 'Build WebGL'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'webgl'
            editor_version: '2020.3.46f1'
            resource_class: 'large'
          project-path: '.'
          build-target: 'WebGL'
          compress: false
          context: Unity
          # Windows Mono
      - unity/build:
          name: 'build-Windows64-mono'
          step-name: 'Build StandaloneWindows64'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'windows-mono'
            editor_version: '2021.3.2f1'
            resource_class: 'large'
          project-path: .
          build-target: 'StandaloneWindows64'
          context: Unity